FROM centos:6

  # Get nodejs set up
  RUN curl -OL https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.gz
  RUN tar -xzf node-v6.9.2-linux-x64.tar.gz
  RUN rm node-v6.9.2-linux-x64.tar.gz
  RUN echo 'export PATH=/node-v6.9.2-linux-x64/bin:$PATH' >>~/.bashrc

  
