# RAPD
#
# VERSION 2.0.0

FROM centos:6.7
MAINTAINER Frank Murphy <fmurphy@anl.gov>

# BASH!
RUN ln -snf /bin/bash /bin/sh

# Needed to build Phenix
RUN rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
RUN yum -y --enablerepo=remi,remi-test install redis
RUN yum -y install blas-devel lapack-devel atlas-sse3-devel atlas-devel openblas-devel libffi-devel ImageMagick-devel git

# Install XDS
# WORKDIR /opt
# ADD XDS-INTEL64_Linux_x86_64.tar .
# RUN /bin/bash -c "echo  'export PATH=/opt/XDS-INTEL64_Linux_x86_64:$PATH' >>/etc/bashrc"

# Install BEST
# ADD best_3.4.4.a_20110819_x86_64_Linux_gfortran.tar best/.
# WORKDIR best
# RUN /bin/bash -c "cp ./best /usr/local/bin/."
# RUN /bin/bash -c "echo 'export besthome=/opt/best' >>/etc/bashrc"

# Install CCP4
# ADD ccp4-7.0-shelx-linux-x86_64.tar.bz2 /opt/
# WORKDIR /opt/ccp4-7.0
# RUN touch $HOME/.agree2ccp4v6
# RUN ./BINARY.setup
# RUN /bin/bash -c "echo 'source /opt/ccp4-7.0/bin/ccp4.setup-sh' >>/etc/bashrc"

# RAPD
WORKDIR /opt
RUN git clone -b sercat https://github.com/RAPD/RAPD.git rapd
WORKDIR /opt/rapd/install
ADD phenix-installer-1.10.1-2155-intel-linux-2.6-x86_64-centos6.tar sources/phenix/
RUN /bin/bash -c "./install -b" # &> /dev/null"
RUN /bin/bash -c "echo 'Finished with rapd install'"
RUN /bin/bash -c "echo 'source /opt/rapd/rapd.shrc' >>/etc/bashrc"

# WORKDIR /opt/rapd/src
