language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    packages:
    - wget
    - subversion
    - git
    - bzip2
    - libncurses5-dev
    - zlib1g-dev
    - libssl-dev
    - pkg-config
    - python
    - build-essential
    - libgl1-mesa-dev
    - libglu1-mesa-dev
install: "install/install -mb"
