d("./js/jquery.flot.0.6.min.js");d("./js/jquery.dataTables.1.7.1.min.js");d("./js/dataTables.fnDisplayRow.min.js");d("./js/jquery.jeegoocontext.1.2.2.min.js");d("./js/thickbox.js");d("./js/jquery.livequery.js");lastcloudID=lastrankID=lastresultID=0;sortTable="";number_images=0;image_string=image_repr="";image_mode="NONE";image_shown="False";cloud_process=cloud_download="1";downloads_active=0;admin="no";waiting_for_cloud=instance_active=instance_local="False";
function e(){downloads_active==0&&$("#download_active").N("slow");setTimeout(f,5E3)}function f(){$("#download-dialog").j("close")}
$(document).X(function(){$("#download-dialog").j({O:false,title:"Download Initiated"});$("#snap_menu_in_process > div").q("inprocessmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(){alert("1")}});$("#snap_menu_share_in_process > div").q("inprocessmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(){}});$("#snap_menu > a > .stac").q("snapmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(){}});$("#snap_menu_share > a").q("snapmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(b,a){if($(a).c("id")>0)switch($(this).c("id")){case "hide-this-snap":$("#snap_menu").find("."+
$(a).c("id")).e("slow");$("#snap_menu_share").find("."+$(a).c("id")).e("slow");$.i("d_hide-this-snap.php",{M:$(a).c("id")});break;case "hide-all-snaps":$("#snap_menu_share").find(".grayed").e("slow");$("#snap_menu").find(".grayed").e("slow");$.i("d_hide-snaps.php",{k:my_datadir});break;case "hide-all":$("#snap_menu_share").find(".grayed").e("slow");$("#snap_menu").find(".grayed").e("slow");$("#run_menu_share").find(".grayed").e("slow");$("#run_menu").find(".grayed").e("slow");$.i("d_hide-snaps.php",
{k:my_datadir});$.i("d_hide-runs.php",{k:my_datadir});break;case "show-success-snaps":$.n({async:false,url:"d_show_success_snaps.php",data:datadir=my_datadir});$("#snap_menu_share").a().remove();$("#snap_menu").a().remove();$("#run_menu_share").a().remove();$("#run_menu").a().remove();lastresultID=0;g("False");break;case "show-all-snaps":$.n({async:false,url:"d_show-snaps.php",data:datadir=my_datadir});$("#snap_menu_share").a().remove();$("#snap_menu").a().remove();$("#run_menu_share").a().remove();
$("#run_menu").a().remove();lastresultID=0;g("False");break;case "show-all":$.n({async:true,url:"d_show-runs.php",data:datadir=my_datadir});$.n({async:false,url:"d_show-snaps.php",data:datadir=my_datadir});$("#snap_menu_share").a().remove();$("#snap_menu").a().remove();$("#run_menu_share").a().remove();$("#run_menu").a().remove();lastresultID=0;g("False");break;case "snap_settings":tb_show("Setings for "+$(a).text(),"d_snap_settings.php?height=380&width=550&result_id="+$(a).c("id")+"&start_repr="+
$(a).text());break;case "snap_header":tb_show("Header information for "+$(a).text(),"d_header.php?height=620&width=550&result_id="+$(a).c("id")+"&start_repr="+$(a).text());break;case "snap_download_image":if(cloud_download=="1"){$.i("get_download.php",{k:my_datadir,id:$(a).c("id"),type:"downimage",A:my_ip});$("#download-dialog").j("open").C(".ui-dialog").find(".ui-dialog-titlebar").remove();$("#download-dialog").j("option","height","auto");waiting_for_cloud="True";e();downloads_active+=1}else alert("Sorry - downloading not currently enabled");
break;case "snap_download_package":if(cloud_download=="1"){$.i("get_download.php",{k:my_datadir,id:$(a).c("id"),type:"downpackage",A:my_ip});$("#download-dialog").j("open").C(".ui-dialog").find(".ui-dialog-titlebar").remove();$("#download-dialog").j("option","height","auto");waiting_for_cloud="True";e();downloads_active+=1}else alert("Sorry - downloading not currently enabled");break;case "snap_reprocess":cloud_process=="1"?tb_show("Reprocessing "+$(a).text(),"d_snap_reprocess.php?height=380&width=570&result_id="+
$(a).c("id")+"&start_repr="+$(a).text()+"&type=reprocess&ip="+my_ip):alert("Sorry - processing not currently enabled");break;case "snap_kappa":cloud_process=="1"?tb_show("Kappa strategy for "+$(a).text(),"d_snap_kappa.php?height=480&width=570&result_id="+$(a).c("id")+"&start_repr="+$(a).text()+"&type=stac&ip="+my_ip):alert("Sorry - processing not currently enabled");break}else alert("Reload the interface - you have a browser error!")}});$("#run_menu > a").q("runmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(){}});
$("#run_menu_share > a").q("runmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(b,a){if($(a).c("id")>0)switch($(this).c("id")){case "hide-this-run":$("#run_menu_share").find("."+$(a).c("id")).e("slow");$("#run_menu").find("."+$(a).c("id")).e("slow");$.i("d_hide-this-run.php",{M:$(a).c("id")});break;case "hide-all-runs":$("#run_menu_share").find(".grayed").e("slow");$("#run_menu").find(".grayed").e("slow");$.i("d_hide-runs.php",{k:my_datadir});break;case "hide-all":$("#snap_menu_share").find(".grayed").e("slow");
$("#snap_menu").find(".grayed").e("slow");$("#run_menu_share").find(".grayed").e("slow");$("#run_menu").find(".grayed").e("slow");$.i("d_hide-snaps.php",{k:my_datadir});$.i("d_hide-runs.php",{k:my_datadir});break;case "show-success-runs":$.n({async:false,url:"d_show-success-runs.php",data:datadir=my_datadir});$("#snap_menu_share").a().remove();$("#snap_menu").a().remove();$("#run_menu_share").a().remove();$("#run_menu").a().remove();lastresultID=0;g("False");break;case "show-all-runs":$.n({async:false,
url:"d_show-runs.php",data:datadir=my_datadir});$("#snap_menu_share").a().remove();$("#snap_menu").a().remove();$("#run_menu_share").a().remove();$("#run_menu").a().remove();lastresultID=0;g("False");break;case "show-all":$.n({async:true,url:"d_show-runs.php",data:datadir=my_datadir});$.n({async:false,url:"d_show-snaps.php",data:datadir=my_datadir});$("#snap_menu_share").a().remove();$("#snap_menu").a().remove();$("#run_menu_share").a().remove();$("#run_menu").a().remove();lastresultID=0;g("False");
break;case "run_settings":tb_show("Setings for "+$(a).text(),"d_run_settings.php?height=300&width=550&result_id="+$(a).c("id")+"&start_repr="+$(a).text()+"&type=reprocess&ip="+my_ip);break;case "run_header":tb_show("Header information for "+$(a).text(),"d_run_header.php?height=620&width=550&result_id="+$(a).c("id")+"&start_repr="+$(a).text());break;case "run_download_process":if(cloud_download=="1"){$.i("get_download.php",{k:my_datadir,id:$(a).c("id"),type:"downproc",A:my_ip});$("#download-dialog").j("open").C(".ui-dialog").find(".ui-dialog-titlebar").remove();
$("#download-dialog").j("option","height","auto");waiting_for_cloud="True";e();downloads_active+=1}else alert("Sorry - downloading not currently enabled");break;case "run_download_image":if(cloud_download=="1"){$.i("get_download.php",{k:my_datadir,id:$(a).c("id"),type:"downimage",A:my_ip});$("#download-dialog").j("open").C(".ui-dialog").find(".ui-dialog-titlebar").remove();$("#download-dialog").j("option","height","auto");waiting_for_cloud="True";e();downloads_active+=1}else alert("Sorry - downloading not currently enabled");
break;case "run_download_package":if(cloud_download=="1"){$.i("get_download.php",{k:my_datadir,id:$(a).c("id"),type:"downpackage",A:my_ip});$("#download-dialog").j("open").C(".ui-dialog").find(".ui-dialog-titlebar").remove();$("#download-dialog").j("option","height","auto");waiting_for_cloud="True";e();downloads_active+=1}else alert("Sorry - downloading not currently enabled");break;case "simple-merge":cloud_process=="1"?tb_show("Merging "+$(a).text(),"d_merge.php?height=150&width=570&result_id="+
$(a).c("id")+"&start_repr="+$(a).text()+"&type=smerge&ip="+my_ip):alert("Sorry - processing not currently enabled");break;case "run_reprocess":cloud_process=="1"?tb_show("Reprocessing "+$(a).text(),"d_reprocess.php?height=630&width=570&result_id="+$(a).c("id")+"&start_repr="+$(a).text()+"&type=reprocess&ip="+my_ip):alert("Sorry - processing not currently enabled");break}else alert("Reload the interface - you have a browser error!")}});$("#run_menu_in_process > div").q("inprocessmenu",{r:true,w:0,
p:1,u:-4,v:-5,t:function(){}});$("#run_menu_share_in_process > div").q("inprocessmenu",{r:true,w:0,p:1,u:-4,v:-5,t:function(b,a){if($(a).c("id"))switch($(this).c("id")){case "hide-this-process":$("."+$(a).c("id")).e("slow");$.i("d_hide-this-process.php",{R:$(a).c("id")});break}}});sortTable=$("#sort-table").Q({aoColumns:[null,null,null,null,null,null,null,null,null,null,null,{bVisible:false}],aaSorting:[[10,"desc"]],bJQueryUI:true,iDisplayLength:25});timeoutID=setTimeout(h,1);$("#sort-table tbody").click(function(b){$(sortTable.I().H).F(function(){$(this.B).b("row_selected")});
$(b.target.parentNode).f("row_selected");b=sortTable.U(sortTable.V(b.target.parentNode))[11];$(".snap_menu_share_wrapper").L({scrollTop:$("#snap_menu_share").a("."+b).G().top-$(".snap_menu_share").G().top-100},500);$(".snap_menu_wrapper").L({scrollTop:$("#snap_menu").a("."+b).G().top-$(".snap_menu").G().top-100},500);$("#snap_menu").a(".clicked").b("clicked");$("#run_menu").a(".clicked").b("clicked");$("#snap_menu_share").a(".clicked").b("clicked");$("#run_menu_share").a(".clicked").b("clicked");
$("#snap_menu").a("."+b).f("clicked");$("#snap_menu_share").a("."+b).f("clicked");j(b)});$("#sort-table thead th").F(function(){switch($(this).text()){case "Mos":this.setAttribute("title","mosaicity estimate");break;case "Res":this.setAttribute("title","resolution estimate");break;case "Stat":this.setAttribute("title","0.6=Good & Higher=Better");break}});$("#tabs1").h({J:true});$("#tabs2").h({J:true});$("#tabs3").h({J:true});$("#tabs2").P("tabsselect",function(b,a){if(a.index==3)if(image_shown=="False"){image_shown=
"True";if(image_mode=="NEW"){$("#mooviewer").show();$("#old_images").empty();load_images(number_images,image_repr,image_string)}}});$("#summary").load("splash.php");$("#download_active").e();$("#mooviewer").e();$("#controller").g("<img src='css/images/LEDs/green-off-16.png'");$("#cluster").g("<img src='css/images/LEDs/green-off-16.png'");$("#dataserver").g("<img src='css/images/LEDs/green-off-16.png'");$("#led_button").e();$("#dialog_link, ul#icons li").W(function(){$(this).f("ui-state-hover")},function(){$(this).b("ui-state-hover")});
$("#snap_menu").D("a","click",function(b){if(!$.o.s&&b.button==0||$.o.s&&b.button==1){var a=$(this).c("id");$("#snap_menu").a().b("clicked");$("#run_menu").a().b("clicked");$("#snap_menu_share").a().b("clicked");$("#run_menu_share").a().b("clicked");$("#snap_menu").find("#"+a).f("clicked");$("#snap_menu_share").find("#"+a).f("clicked");j(a);$(sortTable.I().H).F(function(){$(this.K)[11]==a?$(this.B).f("row_selected"):$(this.B).b("row_selected")});return false}});$("#run_menu").D("a","click",function(b){if(!$.o.s&&
b.button==0||$.o.s&&b.button==1){$("#snap_menu").a().b("clicked");$("#run_menu").a().b("clicked");$("#snap_menu_share").a().b("clicked");$("#run_menu_share").a().b("clicked");$(this).f("clicked");k($(this).c("id"))}});$("#snap_menu_share").D("a","click",function(b){var a=$(this).c("id");if(!$.o.s&&b.button==0||$.o.s&&b.button==1){$("#snap_menu").a().b("clicked");$("#run_menu").a().b("clicked");$("#snap_menu_share").a().b("clicked");$("#run_menu_share").a().b("clicked");$("#snap_menu").find("#"+a).f("clicked");
$("#snap_menu_share").find("#"+a).f("clicked");j(a);$(sortTable.I().H).F(function(){$(this.K)[11]==a?$(this.B).f("row_selected"):$(this.B).b("row_selected")})}});$("#run_menu_share").D("a","click",function(b){if(!$.o.s&&b.button==0||$.o.s&&b.button==1){$("#snap_menu").a().b("clicked");$("#run_menu").a().b("clicked");$("#snap_menu_share").a().b("clicked");$("#run_menu_share").a().b("clicked");$(this).f("clicked");k($(this).c("id"))}});$("#go_to_main").click(function(){document.location.href="main.php"});
$("#go_to_logout").click(function(){document.location.href="login/logout.php"})});function h(){setTimeout(l,5E3);setTimeout(g,1E3);setTimeout(m,1E4);setTimeout(n,5E3)}
function g(b){var a=lastresultID;$.m("d_get_results.php?datadir="+my_datadir+"&id="+lastresultID,function(c){if(c.length){for(i=0;i<c.length-1;i+=5)if(c[i]=="single"){$("#snap_menu_share_in_process").a(".in_process_"+c[2]).e("slow");$("#snap_menu_in_process").a(".in_process_"+c[2]).e("slow");if(c[i+1]!="hide"){$("#snap_menu").g(c[i+3]);$("#snap_menu_share").g(c[i+3]);if(c[i+4]=="FAILED"){$("#snap_menu").a(":first").b("image").f("grayed");$("#snap_menu_share").a(":first").b("image").f("grayed")}else if(c[i+
4]=="REPROCESS"){$("#snap_menu").a(":first").b("image").f("reprocess");$("#snap_menu_share").a(":first").b("image").f("reprocess")}else if(c[i+4]=="STAC"){$("#snap_menu").a(":first").b("image").f("stac");$("#snap_menu_share").a(":first").b("image").f("stac")}}}else if(c[i]=="pair"){$("#snap_menu_share_in_process").a(".in_process_"+c[2]).e("slow");$("#snap_menu_in_process").a(".in_process_"+c[2]).e("slow");if(c[i+1]!="hide"){$("#snap_menu").g(c[i+3]);$("#snap_menu_share").g(c[i+3]);if(c[i+4]=="FAILED"){$("#snap_menu").a(":first").b("image").f("grayed");
$("#snap_menu_share").a(":first").b("image").f("grayed")}else if(c[i+4]=="REPROCESS"){$("#snap_menu").a(":first").b("image").f("reprocess");$("#snap_menu_share").a(":first").b("image").f("reprocess")}}}else if(c[i]=="run"){$("#run_menu_share_in_process").a(".in_process_"+c[2]).e("slow");$("#run_menu_in_process").a(".in_process_"+c[2]).e("slow");if(c[i+1]!="hide"){$("#run_menu").g(c[i+3]);$("#run_menu_share").g(c[i+3]);if(c[i+4]=="FAILED"){$("#run_menu").a(":first").b("image").f("grayed");$("#run_menu_share").a(":first").b("image").f("grayed")}else if(c[i+
4]=="REPROCESS"){$("#run_menu").a(":first").b("image").f("reprocess");$("#run_menu_share").a(":first").b("image").f("reprocess")}}}lastresultID=c[i];a<lastresultID&&o()}if(b!="False")my_timeout_id=instance_active=="True"?setTimeout(g,2E3):setTimeout(g,3E4)})}
function o(){var b=lastrankID;$.m("d_get_rankings.php?datadir="+my_datadir+"&id="+lastrankID,function(a){if(a.length>1){for(i=0;i<a.length-1;i+=12){sortTable.S([a.slice(i,i+12)],false);lastrankID=a[i+11]}sortTable.T()}if(b<lastrankID-5)my_timeout_id=setTimeout(o,1E3)})}
function n(b){$.m("d_get_processes.php?datadir="+my_datadir,function(a){if(a.length)for(i=0;i<a.length-1;i+=5){if(a[i]=="single")if(a[i+1]=="show")if(!$("#snap_menu_share_in_process").find("#"+a[i+2]).length){$("#snap_menu_in_process").g(a[i+4]);$("#snap_menu_share_in_process").g(a[i+4])}if(a[i]=="pair")if(a[i+1]=="show")if(!$("#snap_menu_share_in_process").find("#"+a[i+2]).length){$("#snap_menu_in_process").g(a[i+4]);$("#snap_menu_share_in_process").g(a[i+4])}if(a[i]=="integrate")if(a[i+1]=="show")if(!$("#run_menu_share_in_process").find("#"+
a[i+2]).length){$("#run_menu_in_process").g(a[i+4]);$("#run_menu_share_in_process").g(a[i+4])}}if(b!="False")my_timeout_id=instance_active=="True"?setTimeout(n,5E3):setTimeout(n,3E4)})}
function l(){$.m("get_instance_info.php?datadir="+my_datadir+"&ip="+my_ip,function(b){instance_active=b[0];instance_local=b[1];if(instance_active=="True"){$("#led_button").show();$.m("d_get_status.php?beamline="+my_beamline,function(a){my_beamline=a[0];dataserver_age=a[1];controller_age=a[2];cluster_age=a[3];if(dataserver_age<30){$("#dataserver").a().l().remove();$("#dataserver").g("<img src='css/images/LEDs/green-on-16.png'")}else if(dataserver_age<60){$("#dataserver").a().l().remove();$("#dataserver").g("<img src='css/images/LEDs/yellow-on-16.png'")}else{$("#dataserver").a().l().remove();
$("#dataserver").g("<img src='css/images/LEDs/red-on-16.png'")}if(controller_age<30){$("#controller").a().l().remove();$("#controller").g("<img src='css/images/LEDs/green-on-16.png'")}else if(controller_age<60){$("#controller").a().l().remove();$("#controller").g("<img src='css/images/LEDs/yellow-on-16.png'")}else{$("#controller").a().l().remove();$("#controller").g("<img src='css/images/LEDs/red-on-16.png'")}if(cluster_age<30){$("#cluster").a().l().remove();$("#cluster").g("<img src='css/images/LEDs/green-on-16.png'")}else if(cluster_age<
60){$("#cluster").a().l().remove();$("#cluster").g("<img src='css/images/LEDs/yellow-on-16.png'")}else{$("#cluster").a().l().remove();$("#cluster").g("<img src='css/images/LEDs/red-on-16.png'")}timeoutID=setTimeout(l,3E4)})}else{$("#led_panel").e();timeoutID=setTimeout(l,6E4)}})}
function m(){$.m("d_get_cloud.php?datadir="+my_datadir+"&user="+my_user+"&trip_id="+my_trip_id+"&ip_address="+my_ip+"&id="+lastcloudID,function(b){if(b.length>1){for(i=0;i<b.length-1;i+=3)if(b[i]=="download"){$("#download-iframe").c("src",b[i+1]);$.m("mark_cloud.php?id="+b[i+3]);downloads_active-=1;if(downloads_active==0){$("#download_active").N("slow");waiting_for_cloud="False"}}else{if(b[i+1]=="1"){$("#snap_download_top").d("color","white");$("#snap_download_image").d("color","white");$("#snap_download_package").d("color",
"white");$("#run_download_top").d("color","white");$("#run_download_image").d("color","white");$("#run_download_process").d("color","white");$("#run_download_package").d("color","white");cloud_download="1"}else{$("#snap_download_top").d("color","red");$("#snap_download_image").d("color","red");$("#snap_download_package").d("color","red");$("#run_download_top").d("color","red");$("#run_download_image").d("color","red");$("#run_download_process").d("color","red");$("#run_download_package").d("color",
"red");cloud_download="0"}if(b[i+2]=="1"){$("#snap_reprocess").d("color","white");$("#run_reprocess").d("color","white");$("#simple-merge").d("color","white");cloud_process="1"}else{$("#snap_reprocess").d("color","red");$("#run_reprocess").d("color","red");$("#simple-merge").d("color","red");cloud_process="0"}}lastcloudID=0}waiting_for_cloud=="True"?setTimeout(m,1E4):setTimeout(m,6E4)})}
function j(b){$.m("d_get_result_data.php?res_id="+b+"&datadir="+my_datadir+"&trip_id="+my_trip_id,function(a){if(a.length)if(a[2]=="None"){$("#tabs2-tab1").d("display","list-item");$("#summary").load(a[1]);$("#tabs2").h().h("option","selected")==1&&$("#tabs2").h().h("select",0);$("#stac-summary").empty();$("#tabs2-tab2").d("display","none");$("#tabs2-tab3").d("display","list-item");$("#detail").empty();$("#detail").load(a[3]);$("#tabs2-tab4").d("display","list-item");image_mode=a[4][0];if(image_mode==
"OLD"){image_string=a[4][1];$("#mooviewer").e();$("#old_images").empty();$("#old_images").append(image_string)}else if(image_mode=="NEW"){number_images=a[4][1];image_repr=a[4][2];image_string=a[4][3];if($("#tabs2").h().h("option","selected")==3){$("#old_images").empty();$("#mooviewer").show();load_images(number_images,image_repr,image_string)}else{image_shown="False";$("#old_images").empty();$("#targetframe").empty()}}$("#tabs2-tab5").d("display","list-item");$("#plots").load(a[5])}else{$("#stac-summary").load(a[2]);
$("#tabs2-tab2").d("display","list-item");$("#tabs2").h().h("select",1);$("#tabs2-tab1").d("display","none");$("#tabs2-tab3").d("display","none");$("#tabs2-tab4").d("display","none");$("#tabs2-tab5").d("display","none")}})}
function k(b){$.m("d_get_result_data.php?res_id="+b+"&datadir="+my_datadir+"&trip_id="+my_trip_id,function(a){if(a.length){$("#summary").empty().load(a[1]);$("#tabs2").h().h("option","selected")==1&&$("#tabs2").h().h("select",0);$("#stac-summary").empty();$("#tabs2-tab2").d("display","none");$("#detail").empty();$("#detail").z("<div id='container'><div id='detail1'></div> <div id='detail2'></div> <div id='detail3'></div></div>");$("#detail1").load(a[3][0],function(){$("#detail1").z("<pre>"+$("#detail1").z()+
"</pre>")});$("#detail2").load(a[3][1],function(){$("#detail2").z("<pre>"+$("#detail2").z()+"</pre>")});$("#detail3").load(a[3][2],function(){$("#detail3").z("<pre>"+$("#detail3").z()+"</pre>")});$("#tabs2-tab4").d("display","none");$("#mooviewer").e();$("#old_images").load("run_images.php");$("#plots").empty().load(a[5])}})}function d(b){var a=document.getElementsByTagName("head")[0];script=document.createElement("script");script.src=b;script.type="text/javascript";a.appendChild(script)};
