
CREATE TABLE puck_settings (puckset_id MEDIUMINT(8) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT, beamline VARCHAR(12), A VARCHAR(48), B VARCHAR(48), C VARCHAR(48), D VARCHAR(48), timestamp timestamp DEFAULT CURRENT_TIMESTAMP);

